version: '3.8'

services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
