# docker-compose.yml
services:
  backend:
    build:
      context: ./Servicios/Backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - MLFLOW_TRACKING_URI=https://dagshub.com/JLuisAlmendarez/final-exam-pcd2024-autumn.mlflow
      - PORT=5000
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s
    networks:
      - ml-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Servicios/Frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - ml-network
    restart: unless-stopped

networks:
  ml-network:
    driver: bridge