[project]
name = "final-exam-pcd2024-autumn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagshub>=0.3.45",
    "jupyter>=1.1.1",
    "mlflow>=2.18.0",
    "nltk>=3.9.1",
    "prefect==3.0.3",
]
